from array import *
arr=array('i',[10,20,30,40,50])
print('Original array:',arr)
arr.append(30)
arr.append(60)
print('After appending 30 and 60:',arr)
arr.insert(1,99)
print(' after inserting 99  in 1st position:',arr)
arr.remove(20)
print(' after removing 20:',arr)
n=arr.pop()
print('array after using pop():',arr)
print('popped element:',n)
n=arr.index(30)
print('first occurrence of element 30 is at:',n)
lst=arr.tolist()
print('list:',lst)
print('array:',arr)
