from numpy import *
arr=array([10,20,30.5,-40])
print('original aray:',arr)
print("after adding 5:",arr+5)
print("after substractiion 5",arr-5)
print("after multiplying with 5",arr*5)
print(" after dividing with 5:",arr/5)
print("after modulus with 5:", arr%5)
print("expression value:",(arr+5)**2-10)
print("sin values:",sin(arr))
print("cos vlaues :", cos(arr))
print("tan values:",tan(arr))
print("biggest value:",max(arr))
print("minimum value:",min(arr))
print("sum of elements:",sum(arr))
print("average of all elements:",mean(arr))
